---
- hosts: server1
  become: yes
  become_method: sudo
  roles:
    - mysql-repl-node1

- hosts: server2
  become: yes
  become_method: sudo
  roles:
    - mysql-repl-node2
    
- hosts: server1
  become: yes
  become_method: sudo
  roles:
    - mysql-repl-node1

- hosts: haproxy
  become: yes
  become_method: sudo
  roles:
    - haproxy_mysql

