---

haproxy_user: haproxy
haproxy_group: haproxy
haproxy_web_pass: d41d8cd98f00b2

# Backend settings.
haproxy_backend_name: 'mysql-cluster'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_bind_address: '0.0.0.0'
haproxy_backend_port: 3306
haproxy_backend_mode: 'tcp'

# Frontend settings.
haproxy_frontend_name: 'admin'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 8080
haproxy_frontend_mode: 'http'

#timeout settings
retries: 3
timeout_connect: 3s
timeout_server: 15s
timeout_client: 5s
timeout_queue: 5s
maxconn: 2000
options: check fastinter 1000
